
project_id = "dzispzcdylajxkbufjfd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"

[realtime]
enabled = true

[functions.telegram-auth]
verify_jwt = false

[functions.get-telegram-credentials]
verify_jwt = true

[functions.get-api-key]
verify_jwt = true

[functions.store-api-key]
verify_jwt = true

[functions.fetch-telegram-messages]
verify_jwt = true
