
project_id = "dzispzcdylajxkbufjfd"

[api]
enabled = true
port = 54323
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54321
api_url = "http://localhost"

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 604800
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions]
[functions.get-telegram-credentials]
verify_jwt = true
[functions.telegram-auth]
verify_jwt = false
[functions.store-api-key]
verify_jwt = true
[functions.get-api-key]
verify_jwt = true
