// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbtnmbtdyxoracavaphz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidG5tYnRkeXhvcmFjYXZhcGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NDg4NzQsImV4cCI6MjA1NzEyNDg3NH0.Q912VqlVZI_aNZ-34GfpFWJSBiQ9A4r7Ovx8aswfefU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);