// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzispzcdylajxkbufjfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6aXNwemNkeWxhanhrYnVmamZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTExNDYsImV4cCI6MjA1NzU4NzE0Nn0.DXw5JUS4b3q4SILoEAf_kWvQBm6Jowm1FJocV0AHJck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);